### PR TITLE
Update README file

### PR DESCRIPTION
**Pull request by MichaelHoste**
Hello @armandsar,

I updated the README file for more consistency between https://github.com/aurels/translation-gem
and https://github.com/armandsar/laravel-translationio/

I hope you'll like it that way. Feel free to amend it!

You'll notice that I removed `--dev` from the `composer require` command. If I'm not wrong, we need to require the package in production in order to be able to use GetText syntaxes like `t__` and `n__`.

FYI now that the package seems ready, I will create a specific landing page for Laravel (https://translation.io/laravel) and start a beta-test period to gather feedbacks (I'll reach the Laravel community). I'll keep you in touch.

Thanks again for your support!

I just increased your trial period on Translation.io until 2050. Feel free to create as many free Rails/Laravel projects as you want ;-)

### CODE REVIEW

**Comment by armands2ar** [comment]
Looks amazing!
Just had a though - maybe there should be an option to disable gettext same as in rails gem?

**Comment by armandsar** [comment]
Looks amazing!
Just had a though - maybe there should be an option to disable gettext same as in rails gem?

**Comment by MichaelHoste** [comment]
@armandsar I'm not sure about the option to disable GetText.

There were 2 reasons to disable it in Rails: 

 1. No code parsing so the sync was faster.
 2. Reduced memory footprint for production environments not using it (not so much but it made sense for small VMs with many Rails processes).

(1) is not really an issue in PHP because parsing seems *really* fast already.

For (2) I don't know if there is any way to conditionally not require some dependencies in a Laravel package (so, out of the composer.json file and using a config variable).

Something like.

https://github.com/aurels/translation-gem/blob/75f8f557907443704b81d6d9a9c0b87fd5bb9306/lib/translation.rb#L37

https://github.com/aurels/translation-gem/blob/75f8f557907443704b81d6d9a9c0b87fd5bb9306/lib/translation.rb#L61

Is the production memory footprint really an issue? I don't know exactly what is the size of it, but it shouldn't be *so* much that we need to care about it.

**Comment by armandsar** [comment]
@MichaelHoste those points are fine. 
My only concern was about creating unnecessary mo/po files in git if they wont be used/necessary.
But actually thats not that big a deal, people can just gitignore those if they mind.

**Comment by MichaelHoste** [comment]
@armandsar we can solve this issue by skipping the PO/MO file creation if the response from the server is empty (not really *empty* but with only the PO headers).

It's a good idea actually! I'll create a PR for this soon.

**Pull request merged**
