### PR TITLE
Allow subdirectories for translation PHP files

### PR DESCRIPTION
**Pull request by MichaelHoste**
Accept the Laravel 5 subdirectories structure: {{ trans('foo/bar/foo.key') }}

More info here:
https://laravel.io/forum/02-23-2015-localization-load-files-from-subdirectories-at-resourceslanglocale

(with more tests for sync and sourceEdits)

-------

I also debugged the `SourceEditException` that should have been `SourceEditSyncException`, and some behaviour that was wrong (sourceEdit must been executed before Sync to deal with more situations).

I hope the changes are ok with you.

------

Next, I'll find a way to use the Gettext syntax.

I'm still not sure if I'll use [eusonlito/laravel-Gettext](https://github.com/eusonlito/laravel-Gettext) or build something myself with [oscarotero/Gettext](https://github.com/oscarotero/Gettext). Any thoughts?

### CODE REVIEW

**Comment by MichaelHoste** [comment]
A test doesn't pass in Travis but still pass in my machine.

My wild guess is that the order of files in `Finder::create()->files()->ignoreDotFiles(true)->in($path)` is maybe not the same depending on the system.

So the request body in not build in the same order (but that actually doesn't affect the behaviour).

I'll try to find a way tomorrow to make it pass everywhere.

**Comment by MichaelHoste** [comment]
The failing test works again and everything pass with the latest dependencies.

But it doesn't work with `--prefer-lowest` because of a bug in the YAML library that was fixed since then (https://github.com/symfony/symfony/issues/11109 and https://github.com/symfony/symfony/pull/19304).

It's only needed to make the VCR tests pass (not the actual code) and the only solution I can think of is to revert the body response in a big unreadable single-line but I don't like it.

What do you think about it? Do you know another way to write multi-line YAML? I tried some of [these solutions](https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines) but without success (some quotes are escaped again).

**Comment by armandsar** [comment]
@MichaelHoste vcr also has option to store cassettes in json format, maybe thats a solution

**Comment by MichaelHoste** [comment]
Good idea! I'll try JSON next time I'm going to work on this or find another way to fix these tests.

FYI I already started to draft some code to sync GetText with Translation.io. So we'll be able to use either `__('some.key')` or `_('source text')` in the code. And it seems promising.

**Comment by armandsar** [comment]
@MichaelHoste as for the gettext, I havent used any gettext package for laravel (only rails), best to target most popular probably. Or as you said own implementation would be nice as well.
You can check https://github.com/barryvdh/laravel-translation-manager , they have scanning files for translations, might come in handy

**Comment by MichaelHoste** [comment]
@armandsar I fixed the cassettes to make them pass with the old YAML dependency. I unfortunately didn't find any solution to make them multi-lines :-/

The Gettext implementation is almost ready (I work in this branch: https://github.com/MichaelHoste/laravel-translationio/tree/gettext). But I'll wait until this pull request is merged before creating the new one.

It's still not perfect (no tests, some code to improve, need to find a way to avoid caching issue, etc.), but it scans the code, it creates the PO files and completes them with the backend, and the Gettext methods already works.

I also encapsulated native Gettext methods in new methods like `_i`, `n__()`, `p__()` to allow easier interpolated strings. But the default methods like `_` or `n_` still work.

It's heavily influenced (with some copy/paste) by [eusonlito/laravel-Gettext](https://github.com/eusonlito/laravel-Gettext) and [Belphemur/laravel-gettext](https://github.com/Belphemur/laravel-gettext/) but the only dependecy we need is [oscarotero/Gettext](https://github.com/oscarotero/Gettext) that was already in the project.

**Comment by armandsar** [comment]
:+1:

**Pull request merged**
